
namespace GUI
{
    partial class FrmEditStudent_Teacher
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmEditStudent_Teacher));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.lbl_ClassId = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txt_Id = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnUpload = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.label = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtStudentAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtStudentName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lbl_Class = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pic_StudentAvatar = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.openFilePic = new System.Windows.Forms.OpenFileDialog();
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.txtClassName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtParentName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtParentPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.dtp_StudentDOB = new Bunifu.UI.WinForms.BunifuDatePicker();
            ((System.ComponentModel.ISupportInitialize)(this.pic_StudentAvatar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // lbl_ClassId
            // 
            this.lbl_ClassId.AcceptsReturn = false;
            this.lbl_ClassId.AcceptsTab = false;
            this.lbl_ClassId.AnimationSpeed = 200;
            this.lbl_ClassId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lbl_ClassId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lbl_ClassId.BackColor = System.Drawing.Color.Transparent;
            this.lbl_ClassId.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lbl_ClassId.BackgroundImage")));
            this.lbl_ClassId.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.lbl_ClassId.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lbl_ClassId.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.lbl_ClassId.BorderColorIdle = System.Drawing.SystemColors.Control;
            this.lbl_ClassId.BorderRadius = 10;
            this.lbl_ClassId.BorderThickness = 1;
            this.lbl_ClassId.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lbl_ClassId.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lbl_ClassId.DefaultFont = new System.Drawing.Font("Garamond", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_ClassId.DefaultText = "";
            this.lbl_ClassId.FillColor = System.Drawing.SystemColors.Control;
            this.lbl_ClassId.ForeColor = System.Drawing.Color.Olive;
            this.lbl_ClassId.HideSelection = true;
            this.lbl_ClassId.IconLeft = null;
            this.lbl_ClassId.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lbl_ClassId.IconPadding = 10;
            this.lbl_ClassId.IconRight = null;
            this.lbl_ClassId.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lbl_ClassId.Lines = new string[0];
            this.lbl_ClassId.Location = new System.Drawing.Point(134, 45);
            this.lbl_ClassId.MaxLength = 32767;
            this.lbl_ClassId.MinimumSize = new System.Drawing.Size(1, 1);
            this.lbl_ClassId.Modified = false;
            this.lbl_ClassId.Multiline = false;
            this.lbl_ClassId.Name = "lbl_ClassId";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lbl_ClassId.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lbl_ClassId.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lbl_ClassId.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.SystemColors.Control;
            stateProperties4.FillColor = System.Drawing.SystemColors.Control;
            stateProperties4.ForeColor = System.Drawing.Color.Olive;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lbl_ClassId.OnIdleState = stateProperties4;
            this.lbl_ClassId.Padding = new System.Windows.Forms.Padding(3);
            this.lbl_ClassId.PasswordChar = '\0';
            this.lbl_ClassId.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.lbl_ClassId.PlaceholderText = "id";
            this.lbl_ClassId.ReadOnly = true;
            this.lbl_ClassId.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lbl_ClassId.SelectedText = "";
            this.lbl_ClassId.SelectionLength = 0;
            this.lbl_ClassId.SelectionStart = 0;
            this.lbl_ClassId.ShortcutsEnabled = true;
            this.lbl_ClassId.Size = new System.Drawing.Size(41, 43);
            this.lbl_ClassId.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lbl_ClassId.TabIndex = 144;
            this.lbl_ClassId.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lbl_ClassId.TextMarginBottom = 0;
            this.lbl_ClassId.TextMarginLeft = 3;
            this.lbl_ClassId.TextMarginTop = 0;
            this.lbl_ClassId.TextPlaceholder = "id";
            this.lbl_ClassId.UseSystemPasswordChar = false;
            this.lbl_ClassId.WordWrap = true;
            // 
            // txt_Id
            // 
            this.txt_Id.AcceptsReturn = false;
            this.txt_Id.AcceptsTab = false;
            this.txt_Id.AnimationSpeed = 200;
            this.txt_Id.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Id.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Id.BackColor = System.Drawing.Color.Transparent;
            this.txt_Id.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Id.BackgroundImage")));
            this.txt_Id.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Id.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Id.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Id.BorderColorIdle = System.Drawing.SystemColors.Control;
            this.txt_Id.BorderRadius = 10;
            this.txt_Id.BorderThickness = 1;
            this.txt_Id.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Id.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Id.DefaultFont = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_Id.DefaultText = "";
            this.txt_Id.FillColor = System.Drawing.SystemColors.Control;
            this.txt_Id.ForeColor = System.Drawing.Color.Olive;
            this.txt_Id.HideSelection = true;
            this.txt_Id.IconLeft = null;
            this.txt_Id.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Id.IconPadding = 10;
            this.txt_Id.IconRight = null;
            this.txt_Id.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Id.Lines = new string[0];
            this.txt_Id.Location = new System.Drawing.Point(134, 42);
            this.txt_Id.MaxLength = 32767;
            this.txt_Id.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Id.Modified = false;
            this.txt_Id.Multiline = false;
            this.txt_Id.Name = "txt_Id";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Id.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Id.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Id.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.SystemColors.Control;
            stateProperties8.FillColor = System.Drawing.SystemColors.Control;
            stateProperties8.ForeColor = System.Drawing.Color.Olive;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Id.OnIdleState = stateProperties8;
            this.txt_Id.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Id.PasswordChar = '\0';
            this.txt_Id.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txt_Id.PlaceholderText = "Student ID";
            this.txt_Id.ReadOnly = true;
            this.txt_Id.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Id.SelectedText = "";
            this.txt_Id.SelectionLength = 0;
            this.txt_Id.SelectionStart = 0;
            this.txt_Id.ShortcutsEnabled = true;
            this.txt_Id.Size = new System.Drawing.Size(34, 46);
            this.txt_Id.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Id.TabIndex = 143;
            this.txt_Id.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Id.TextMarginBottom = 0;
            this.txt_Id.TextMarginLeft = 3;
            this.txt_Id.TextMarginTop = 0;
            this.txt_Id.TextPlaceholder = "Student ID";
            this.txt_Id.UseSystemPasswordChar = false;
            this.txt_Id.WordWrap = true;
            // 
            // btnUpload
            // 
            this.btnUpload.AllowAnimations = true;
            this.btnUpload.AllowMouseEffects = true;
            this.btnUpload.AllowToggling = false;
            this.btnUpload.AnimationSpeed = 200;
            this.btnUpload.AutoGenerateColors = false;
            this.btnUpload.AutoRoundBorders = false;
            this.btnUpload.AutoSizeLeftIcon = true;
            this.btnUpload.AutoSizeRightIcon = true;
            this.btnUpload.BackColor = System.Drawing.Color.Transparent;
            this.btnUpload.BackColor1 = System.Drawing.Color.Navy;
            this.btnUpload.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpload.BackgroundImage")));
            this.btnUpload.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.btnUpload.ButtonText = "Upload";
            this.btnUpload.ButtonTextMarginLeft = 0;
            this.btnUpload.ColorContrastOnClick = 45;
            this.btnUpload.ColorContrastOnHover = 45;
            this.btnUpload.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnUpload.CustomizableEdges = borderEdges1;
            this.btnUpload.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpload.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpload.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpload.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpload.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUpload.Font = new System.Drawing.Font("Garamond", 12F);
            this.btnUpload.ForeColor = System.Drawing.Color.White;
            this.btnUpload.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpload.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpload.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUpload.IconMarginLeft = 11;
            this.btnUpload.IconPadding = 10;
            this.btnUpload.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpload.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpload.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpload.IconSize = 25;
            this.btnUpload.IdleBorderColor = System.Drawing.Color.FloralWhite;
            this.btnUpload.IdleBorderRadius = 20;
            this.btnUpload.IdleBorderThickness = 1;
            this.btnUpload.IdleFillColor = System.Drawing.Color.Navy;
            this.btnUpload.IdleIconLeftImage = null;
            this.btnUpload.IdleIconRightImage = null;
            this.btnUpload.IndicateFocus = false;
            this.btnUpload.Location = new System.Drawing.Point(87, 435);
            this.btnUpload.Name = "btnUpload";
            this.btnUpload.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpload.OnDisabledState.BorderRadius = 20;
            this.btnUpload.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpload.OnDisabledState.BorderThickness = 1;
            this.btnUpload.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpload.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpload.OnDisabledState.IconLeftImage = null;
            this.btnUpload.OnDisabledState.IconRightImage = null;
            this.btnUpload.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpload.onHoverState.BorderRadius = 20;
            this.btnUpload.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpload.onHoverState.BorderThickness = 1;
            this.btnUpload.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpload.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUpload.onHoverState.IconLeftImage = null;
            this.btnUpload.onHoverState.IconRightImage = null;
            this.btnUpload.OnIdleState.BorderColor = System.Drawing.Color.FloralWhite;
            this.btnUpload.OnIdleState.BorderRadius = 20;
            this.btnUpload.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.btnUpload.OnIdleState.BorderThickness = 1;
            this.btnUpload.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.btnUpload.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUpload.OnIdleState.IconLeftImage = null;
            this.btnUpload.OnIdleState.IconRightImage = null;
            this.btnUpload.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpload.OnPressedState.BorderRadius = 20;
            this.btnUpload.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpload.OnPressedState.BorderThickness = 1;
            this.btnUpload.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpload.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUpload.OnPressedState.IconLeftImage = null;
            this.btnUpload.OnPressedState.IconRightImage = null;
            this.btnUpload.Size = new System.Drawing.Size(145, 39);
            this.btnUpload.TabIndex = 142;
            this.btnUpload.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpload.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpload.TextMarginLeft = 0;
            this.btnUpload.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUpload.UseDefaultRadiusAndThickness = true;
            this.btnUpload.Click += new System.EventHandler(this.btnUpload_Click);
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel6.Location = new System.Drawing.Point(393, 401);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(77, 26);
            this.bunifuLabel6.TabIndex = 141;
            this.bunifuLabel6.Text = "ID Class";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // label
            // 
            this.label.AllowParentOverrides = false;
            this.label.AutoEllipsis = false;
            this.label.Cursor = System.Windows.Forms.Cursors.Default;
            this.label.CursorType = System.Windows.Forms.Cursors.Default;
            this.label.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label.ForeColor = System.Drawing.Color.Olive;
            this.label.Location = new System.Drawing.Point(13, 51);
            this.label.Name = "label";
            this.label.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.label.Size = new System.Drawing.Size(115, 26);
            this.label.TabIndex = 140;
            this.label.Text = "Student ID:";
            this.label.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.label.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.Navy;
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges2;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Garamond", 12F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.FloralWhite;
            this.btnSave.IdleBorderRadius = 20;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.Navy;
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(606, 435);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 20;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 20;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.FloralWhite;
            this.btnSave.OnIdleState.BorderRadius = 20;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 20;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(144, 39);
            this.btnSave.TabIndex = 139;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // txtStudentAddress
            // 
            this.txtStudentAddress.AcceptsReturn = false;
            this.txtStudentAddress.AcceptsTab = false;
            this.txtStudentAddress.AnimationSpeed = 200;
            this.txtStudentAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStudentAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStudentAddress.BackColor = System.Drawing.Color.Transparent;
            this.txtStudentAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStudentAddress.BackgroundImage")));
            this.txtStudentAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtStudentAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStudentAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtStudentAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStudentAddress.BorderRadius = 10;
            this.txtStudentAddress.BorderThickness = 1;
            this.txtStudentAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStudentAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtStudentAddress.DefaultText = "";
            this.txtStudentAddress.FillColor = System.Drawing.Color.White;
            this.txtStudentAddress.HideSelection = true;
            this.txtStudentAddress.IconLeft = global::GUI.Properties.Resources.home;
            this.txtStudentAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentAddress.IconPadding = 10;
            this.txtStudentAddress.IconRight = null;
            this.txtStudentAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentAddress.Lines = new string[0];
            this.txtStudentAddress.Location = new System.Drawing.Point(393, 252);
            this.txtStudentAddress.MaxLength = 32767;
            this.txtStudentAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStudentAddress.Modified = false;
            this.txtStudentAddress.Multiline = false;
            this.txtStudentAddress.Name = "txtStudentAddress";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentAddress.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStudentAddress.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentAddress.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentAddress.OnIdleState = stateProperties12;
            this.txtStudentAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtStudentAddress.PasswordChar = '\0';
            this.txtStudentAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStudentAddress.PlaceholderText = "Enter student\'s address";
            this.txtStudentAddress.ReadOnly = false;
            this.txtStudentAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStudentAddress.SelectedText = "";
            this.txtStudentAddress.SelectionLength = 0;
            this.txtStudentAddress.SelectionStart = 0;
            this.txtStudentAddress.ShortcutsEnabled = true;
            this.txtStudentAddress.Size = new System.Drawing.Size(362, 41);
            this.txtStudentAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStudentAddress.TabIndex = 137;
            this.txtStudentAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStudentAddress.TextMarginBottom = 0;
            this.txtStudentAddress.TextMarginLeft = 3;
            this.txtStudentAddress.TextMarginTop = 0;
            this.txtStudentAddress.TextPlaceholder = "Enter student\'s address";
            this.txtStudentAddress.UseSystemPasswordChar = false;
            this.txtStudentAddress.WordWrap = true;
            // 
            // txtStudentName
            // 
            this.txtStudentName.AcceptsReturn = false;
            this.txtStudentName.AcceptsTab = false;
            this.txtStudentName.AnimationSpeed = 200;
            this.txtStudentName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStudentName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStudentName.BackColor = System.Drawing.Color.Transparent;
            this.txtStudentName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStudentName.BackgroundImage")));
            this.txtStudentName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtStudentName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStudentName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtStudentName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStudentName.BorderRadius = 10;
            this.txtStudentName.BorderThickness = 1;
            this.txtStudentName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStudentName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtStudentName.DefaultText = "";
            this.txtStudentName.FillColor = System.Drawing.Color.White;
            this.txtStudentName.HideSelection = true;
            this.txtStudentName.IconLeft = global::GUI.Properties.Resources.usericon;
            this.txtStudentName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentName.IconPadding = 10;
            this.txtStudentName.IconRight = null;
            this.txtStudentName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentName.Lines = new string[0];
            this.txtStudentName.Location = new System.Drawing.Point(393, 160);
            this.txtStudentName.MaxLength = 32767;
            this.txtStudentName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStudentName.Modified = false;
            this.txtStudentName.Multiline = false;
            this.txtStudentName.Name = "txtStudentName";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStudentName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentName.OnIdleState = stateProperties16;
            this.txtStudentName.Padding = new System.Windows.Forms.Padding(3);
            this.txtStudentName.PasswordChar = '\0';
            this.txtStudentName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStudentName.PlaceholderText = "Enter student\'s name";
            this.txtStudentName.ReadOnly = false;
            this.txtStudentName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStudentName.SelectedText = "";
            this.txtStudentName.SelectionLength = 0;
            this.txtStudentName.SelectionStart = 0;
            this.txtStudentName.ShortcutsEnabled = true;
            this.txtStudentName.Size = new System.Drawing.Size(362, 41);
            this.txtStudentName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStudentName.TabIndex = 138;
            this.txtStudentName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStudentName.TextMarginBottom = 0;
            this.txtStudentName.TextMarginLeft = 3;
            this.txtStudentName.TextMarginTop = 0;
            this.txtStudentName.TextPlaceholder = "Enter student\'s name";
            this.txtStudentName.UseSystemPasswordChar = false;
            this.txtStudentName.WordWrap = true;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel1.Location = new System.Drawing.Point(393, 220);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(74, 26);
            this.bunifuLabel1.TabIndex = 132;
            this.bunifuLabel1.Text = " Address";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lbl_Class
            // 
            this.lbl_Class.AllowParentOverrides = false;
            this.lbl_Class.AutoEllipsis = false;
            this.lbl_Class.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_Class.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_Class.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_Class.ForeColor = System.Drawing.Color.DarkGray;
            this.lbl_Class.Location = new System.Drawing.Point(631, 406);
            this.lbl_Class.Name = "lbl_Class";
            this.lbl_Class.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_Class.Size = new System.Drawing.Size(0, 0);
            this.lbl_Class.TabIndex = 133;
            this.lbl_Class.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_Class.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel5.Location = new System.Drawing.Point(575, 406);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(0, 0);
            this.bunifuLabel5.TabIndex = 134;
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel3.Location = new System.Drawing.Point(393, 128);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(55, 26);
            this.bunifuLabel3.TabIndex = 135;
            this.bunifuLabel3.Text = "Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Garamond", 19.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.DarkRed;
            this.bunifuLabel2.Location = new System.Drawing.Point(430, 72);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(273, 37);
            this.bunifuLabel2.TabIndex = 130;
            this.bunifuLabel2.Text = "Edit Student Profile";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pic_StudentAvatar
            // 
            this.pic_StudentAvatar.AllowFocused = false;
            this.pic_StudentAvatar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pic_StudentAvatar.AutoSizeHeight = true;
            this.pic_StudentAvatar.BorderRadius = 147;
            this.pic_StudentAvatar.Image = ((System.Drawing.Image)(resources.GetObject("pic_StudentAvatar.Image")));
            this.pic_StudentAvatar.IsCircle = true;
            this.pic_StudentAvatar.Location = new System.Drawing.Point(25, 89);
            this.pic_StudentAvatar.Name = "pic_StudentAvatar";
            this.pic_StudentAvatar.Size = new System.Drawing.Size(295, 295);
            this.pic_StudentAvatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pic_StudentAvatar.TabIndex = 129;
            this.pic_StudentAvatar.TabStop = false;
            this.pic_StudentAvatar.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = false;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // openFilePic
            // 
            this.openFilePic.FileName = "openFileDialog1";
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // txtClassName
            // 
            this.txtClassName.AcceptsReturn = false;
            this.txtClassName.AcceptsTab = false;
            this.txtClassName.AnimationSpeed = 200;
            this.txtClassName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtClassName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtClassName.BackColor = System.Drawing.Color.Transparent;
            this.txtClassName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtClassName.BackgroundImage")));
            this.txtClassName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtClassName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtClassName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtClassName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtClassName.BorderRadius = 10;
            this.txtClassName.BorderThickness = 1;
            this.txtClassName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtClassName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClassName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtClassName.DefaultText = "";
            this.txtClassName.FillColor = System.Drawing.Color.White;
            this.txtClassName.HideSelection = true;
            this.txtClassName.IconLeft = global::GUI.Properties.Resources.edit;
            this.txtClassName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClassName.IconPadding = 10;
            this.txtClassName.IconRight = null;
            this.txtClassName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtClassName.Lines = new string[0];
            this.txtClassName.Location = new System.Drawing.Point(393, 433);
            this.txtClassName.MaxLength = 32767;
            this.txtClassName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtClassName.Modified = false;
            this.txtClassName.Multiline = false;
            this.txtClassName.Name = "txtClassName";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClassName.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtClassName.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClassName.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtClassName.OnIdleState = stateProperties28;
            this.txtClassName.Padding = new System.Windows.Forms.Padding(3);
            this.txtClassName.PasswordChar = '\0';
            this.txtClassName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtClassName.PlaceholderText = "Class Name";
            this.txtClassName.ReadOnly = true;
            this.txtClassName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtClassName.SelectedText = "";
            this.txtClassName.SelectionLength = 0;
            this.txtClassName.SelectionStart = 0;
            this.txtClassName.ShortcutsEnabled = true;
            this.txtClassName.Size = new System.Drawing.Size(141, 41);
            this.txtClassName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtClassName.TabIndex = 145;
            this.txtClassName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtClassName.TextMarginBottom = 0;
            this.txtClassName.TextMarginLeft = 3;
            this.txtClassName.TextMarginTop = 0;
            this.txtClassName.TextPlaceholder = "Class Name";
            this.txtClassName.UseSystemPasswordChar = false;
            this.txtClassName.WordWrap = true;
            // 
            // txtParentName
            // 
            this.txtParentName.AcceptsReturn = false;
            this.txtParentName.AcceptsTab = false;
            this.txtParentName.AnimationSpeed = 200;
            this.txtParentName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtParentName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtParentName.BackColor = System.Drawing.Color.Transparent;
            this.txtParentName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtParentName.BackgroundImage")));
            this.txtParentName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtParentName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtParentName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtParentName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtParentName.BorderRadius = 10;
            this.txtParentName.BorderThickness = 1;
            this.txtParentName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtParentName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtParentName.DefaultText = "";
            this.txtParentName.FillColor = System.Drawing.Color.White;
            this.txtParentName.HideSelection = true;
            this.txtParentName.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtParentName.IconLeft")));
            this.txtParentName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentName.IconPadding = 10;
            this.txtParentName.IconRight = null;
            this.txtParentName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentName.Lines = new string[0];
            this.txtParentName.Location = new System.Drawing.Point(596, 343);
            this.txtParentName.MaxLength = 32767;
            this.txtParentName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtParentName.Modified = false;
            this.txtParentName.Multiline = false;
            this.txtParentName.Name = "txtParentName";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentName.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtParentName.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentName.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentName.OnIdleState = stateProperties20;
            this.txtParentName.Padding = new System.Windows.Forms.Padding(3);
            this.txtParentName.PasswordChar = '\0';
            this.txtParentName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtParentName.PlaceholderText = "Enter student\'s parent phone number";
            this.txtParentName.ReadOnly = false;
            this.txtParentName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtParentName.SelectedText = "";
            this.txtParentName.SelectionLength = 0;
            this.txtParentName.SelectionStart = 0;
            this.txtParentName.ShortcutsEnabled = true;
            this.txtParentName.Size = new System.Drawing.Size(159, 41);
            this.txtParentName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtParentName.TabIndex = 148;
            this.txtParentName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtParentName.TextMarginBottom = 0;
            this.txtParentName.TextMarginLeft = 3;
            this.txtParentName.TextMarginTop = 0;
            this.txtParentName.TextPlaceholder = "Enter student\'s parent phone number";
            this.txtParentName.UseSystemPasswordChar = false;
            this.txtParentName.WordWrap = true;
            // 
            // txtParentPhone
            // 
            this.txtParentPhone.AcceptsReturn = false;
            this.txtParentPhone.AcceptsTab = false;
            this.txtParentPhone.AnimationSpeed = 200;
            this.txtParentPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtParentPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtParentPhone.BackColor = System.Drawing.Color.Transparent;
            this.txtParentPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtParentPhone.BackgroundImage")));
            this.txtParentPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtParentPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtParentPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtParentPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtParentPhone.BorderRadius = 10;
            this.txtParentPhone.BorderThickness = 1;
            this.txtParentPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtParentPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtParentPhone.DefaultText = "";
            this.txtParentPhone.FillColor = System.Drawing.Color.White;
            this.txtParentPhone.HideSelection = true;
            this.txtParentPhone.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtParentPhone.IconLeft")));
            this.txtParentPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentPhone.IconPadding = 10;
            this.txtParentPhone.IconRight = null;
            this.txtParentPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentPhone.Lines = new string[0];
            this.txtParentPhone.Location = new System.Drawing.Point(393, 343);
            this.txtParentPhone.MaxLength = 32767;
            this.txtParentPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtParentPhone.Modified = false;
            this.txtParentPhone.Multiline = false;
            this.txtParentPhone.Name = "txtParentPhone";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentPhone.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtParentPhone.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentPhone.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentPhone.OnIdleState = stateProperties24;
            this.txtParentPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtParentPhone.PasswordChar = '\0';
            this.txtParentPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtParentPhone.PlaceholderText = "Enter student\'s parent phone number";
            this.txtParentPhone.ReadOnly = false;
            this.txtParentPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtParentPhone.SelectedText = "";
            this.txtParentPhone.SelectionLength = 0;
            this.txtParentPhone.SelectionStart = 0;
            this.txtParentPhone.ShortcutsEnabled = true;
            this.txtParentPhone.Size = new System.Drawing.Size(197, 41);
            this.txtParentPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtParentPhone.TabIndex = 147;
            this.txtParentPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtParentPhone.TextMarginBottom = 0;
            this.txtParentPhone.TextMarginLeft = 3;
            this.txtParentPhone.TextMarginTop = 0;
            this.txtParentPhone.TextPlaceholder = "Enter student\'s parent phone number";
            this.txtParentPhone.UseSystemPasswordChar = false;
            this.txtParentPhone.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel4.Location = new System.Drawing.Point(393, 311);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(208, 26);
            this.bunifuLabel4.TabIndex = 146;
            this.bunifuLabel4.Text = "Parent Phone & Name";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // dtp_StudentDOB
            // 
            this.dtp_StudentDOB.BackColor = System.Drawing.Color.White;
            this.dtp_StudentDOB.BorderRadius = 1;
            this.dtp_StudentDOB.CalendarForeColor = System.Drawing.Color.Navy;
            this.dtp_StudentDOB.CalendarMonthBackground = System.Drawing.SystemColors.HighlightText;
            this.dtp_StudentDOB.CalendarTrailingForeColor = System.Drawing.SystemColors.Control;
            this.dtp_StudentDOB.Color = System.Drawing.Color.Silver;
            this.dtp_StudentDOB.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtp_StudentDOB.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtp_StudentDOB.DisabledColor = System.Drawing.Color.Gray;
            this.dtp_StudentDOB.DisplayWeekNumbers = false;
            this.dtp_StudentDOB.DPHeight = 0;
            this.dtp_StudentDOB.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtp_StudentDOB.FillDatePicker = false;
            this.dtp_StudentDOB.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtp_StudentDOB.ForeColor = System.Drawing.Color.Black;
            this.dtp_StudentDOB.Icon = ((System.Drawing.Image)(resources.GetObject("dtp_StudentDOB.Icon")));
            this.dtp_StudentDOB.IconColor = System.Drawing.Color.Gray;
            this.dtp_StudentDOB.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtp_StudentDOB.LeftTextMargin = 5;
            this.dtp_StudentDOB.Location = new System.Drawing.Point(67, 389);
            this.dtp_StudentDOB.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtp_StudentDOB.Name = "dtp_StudentDOB";
            this.dtp_StudentDOB.Size = new System.Drawing.Size(196, 32);
            this.dtp_StudentDOB.TabIndex = 149;
            // 
            // FrmEditStudent_Teacher
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(811, 499);
            this.Controls.Add(this.dtp_StudentDOB);
            this.Controls.Add(this.txtParentName);
            this.Controls.Add(this.txtParentPhone);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.txtClassName);
            this.Controls.Add(this.lbl_ClassId);
            this.Controls.Add(this.txt_Id);
            this.Controls.Add(this.btnUpload);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.label);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.txtStudentAddress);
            this.Controls.Add(this.txtStudentName);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.lbl_Class);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.pic_StudentAvatar);
            this.HeaderBackColor = System.Drawing.Color.Navy;
            this.Name = "FrmEditStudent_Teacher";
            this.Text = "Edit Student Form";
            this.Load += new System.EventHandler(this.FrmEditStudent_Load);
            this.Controls.SetChildIndex(this.pic_StudentAvatar, 0);
            this.Controls.SetChildIndex(this.bunifuLabel2, 0);
            this.Controls.SetChildIndex(this.bunifuLabel3, 0);
            this.Controls.SetChildIndex(this.bunifuLabel5, 0);
            this.Controls.SetChildIndex(this.lbl_Class, 0);
            this.Controls.SetChildIndex(this.bunifuLabel1, 0);
            this.Controls.SetChildIndex(this.txtStudentName, 0);
            this.Controls.SetChildIndex(this.txtStudentAddress, 0);
            this.Controls.SetChildIndex(this.btnSave, 0);
            this.Controls.SetChildIndex(this.label, 0);
            this.Controls.SetChildIndex(this.bunifuLabel6, 0);
            this.Controls.SetChildIndex(this.btnUpload, 0);
            this.Controls.SetChildIndex(this.txt_Id, 0);
            this.Controls.SetChildIndex(this.lbl_ClassId, 0);
            this.Controls.SetChildIndex(this.txtClassName, 0);
            this.Controls.SetChildIndex(this.bunifuLabel4, 0);
            this.Controls.SetChildIndex(this.txtParentPhone, 0);
            this.Controls.SetChildIndex(this.txtParentName, 0);
            this.Controls.SetChildIndex(this.dtp_StudentDOB, 0);
            ((System.ComponentModel.ISupportInitialize)(this.pic_StudentAvatar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuTextBox lbl_ClassId;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Id;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUpload;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuLabel label;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuTextBox txtStudentAddress;
        private Bunifu.UI.WinForms.BunifuTextBox txtStudentName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel lbl_Class;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuPictureBox pic_StudentAvatar;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private System.Windows.Forms.OpenFileDialog openFilePic;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuTextBox txtClassName;
        private Bunifu.UI.WinForms.BunifuTextBox txtParentName;
        private Bunifu.UI.WinForms.BunifuTextBox txtParentPhone;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuDatePicker dtp_StudentDOB;
    }
}