
namespace GUI
{
    partial class FrmStudent
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FrmStudent));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.btnSave = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtParentPhone = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtStudentAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtStudentName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.lbl_Class = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.pic_StudentAvatar = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.errorProvider1 = new System.Windows.Forms.ErrorProvider(this.components);
            this.bunifuSnackbar1 = new Bunifu.UI.WinForms.BunifuSnackbar(this.components);
            this.openFilePic = new System.Windows.Forms.OpenFileDialog();
            this.btnUpload = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.drp_Classroom = new Bunifu.UI.WinForms.BunifuDropdown();
            this.lbl_ClassId = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtParentName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.dtp_StudentDOB = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.txt_Id = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.pic_StudentAvatar)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).BeginInit();
            this.SuspendLayout();
            // 
            // btnSave
            // 
            this.btnSave.AllowAnimations = true;
            this.btnSave.AllowMouseEffects = true;
            this.btnSave.AllowToggling = false;
            this.btnSave.AnimationSpeed = 200;
            this.btnSave.AutoGenerateColors = false;
            this.btnSave.AutoRoundBorders = false;
            this.btnSave.AutoSizeLeftIcon = true;
            this.btnSave.AutoSizeRightIcon = true;
            this.btnSave.BackColor = System.Drawing.Color.Transparent;
            this.btnSave.BackColor1 = System.Drawing.Color.Navy;
            this.btnSave.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSave.BackgroundImage")));
            this.btnSave.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.btnSave.ButtonText = "Save";
            this.btnSave.ButtonTextMarginLeft = 0;
            this.btnSave.ColorContrastOnClick = 45;
            this.btnSave.ColorContrastOnHover = 45;
            this.btnSave.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnSave.CustomizableEdges = borderEdges5;
            this.btnSave.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSave.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSave.Font = new System.Drawing.Font("Garamond", 12F);
            this.btnSave.ForeColor = System.Drawing.Color.White;
            this.btnSave.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSave.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSave.IconMarginLeft = 11;
            this.btnSave.IconPadding = 10;
            this.btnSave.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSave.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnSave.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSave.IconSize = 25;
            this.btnSave.IdleBorderColor = System.Drawing.Color.FloralWhite;
            this.btnSave.IdleBorderRadius = 20;
            this.btnSave.IdleBorderThickness = 1;
            this.btnSave.IdleFillColor = System.Drawing.Color.Navy;
            this.btnSave.IdleIconLeftImage = null;
            this.btnSave.IdleIconRightImage = null;
            this.btnSave.IndicateFocus = false;
            this.btnSave.Location = new System.Drawing.Point(596, 428);
            this.btnSave.Name = "btnSave";
            this.btnSave.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSave.OnDisabledState.BorderRadius = 20;
            this.btnSave.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnDisabledState.BorderThickness = 1;
            this.btnSave.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSave.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSave.OnDisabledState.IconLeftImage = null;
            this.btnSave.OnDisabledState.IconRightImage = null;
            this.btnSave.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.BorderRadius = 20;
            this.btnSave.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.onHoverState.BorderThickness = 1;
            this.btnSave.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnSave.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSave.onHoverState.IconLeftImage = null;
            this.btnSave.onHoverState.IconRightImage = null;
            this.btnSave.OnIdleState.BorderColor = System.Drawing.Color.FloralWhite;
            this.btnSave.OnIdleState.BorderRadius = 20;
            this.btnSave.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.btnSave.OnIdleState.BorderThickness = 1;
            this.btnSave.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.btnSave.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnIdleState.IconLeftImage = null;
            this.btnSave.OnIdleState.IconRightImage = null;
            this.btnSave.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.BorderRadius = 20;
            this.btnSave.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSave.OnPressedState.BorderThickness = 1;
            this.btnSave.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnSave.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSave.OnPressedState.IconLeftImage = null;
            this.btnSave.OnPressedState.IconRightImage = null;
            this.btnSave.Size = new System.Drawing.Size(144, 39);
            this.btnSave.TabIndex = 101;
            this.btnSave.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSave.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSave.TextMarginLeft = 0;
            this.btnSave.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSave.UseDefaultRadiusAndThickness = true;
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // txtParentPhone
            // 
            this.txtParentPhone.AcceptsReturn = false;
            this.txtParentPhone.AcceptsTab = false;
            this.txtParentPhone.AnimationSpeed = 200;
            this.txtParentPhone.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtParentPhone.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtParentPhone.BackColor = System.Drawing.Color.Transparent;
            this.txtParentPhone.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtParentPhone.BackgroundImage")));
            this.txtParentPhone.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtParentPhone.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtParentPhone.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtParentPhone.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtParentPhone.BorderRadius = 10;
            this.txtParentPhone.BorderThickness = 1;
            this.txtParentPhone.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtParentPhone.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentPhone.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtParentPhone.DefaultText = "";
            this.txtParentPhone.FillColor = System.Drawing.Color.White;
            this.txtParentPhone.HideSelection = true;
            this.txtParentPhone.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtParentPhone.IconLeft")));
            this.txtParentPhone.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentPhone.IconPadding = 10;
            this.txtParentPhone.IconRight = null;
            this.txtParentPhone.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentPhone.Lines = new string[0];
            this.txtParentPhone.Location = new System.Drawing.Point(386, 333);
            this.txtParentPhone.MaxLength = 32767;
            this.txtParentPhone.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtParentPhone.Modified = false;
            this.txtParentPhone.Multiline = false;
            this.txtParentPhone.Name = "txtParentPhone";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentPhone.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtParentPhone.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentPhone.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentPhone.OnIdleState = stateProperties52;
            this.txtParentPhone.Padding = new System.Windows.Forms.Padding(3);
            this.txtParentPhone.PasswordChar = '\0';
            this.txtParentPhone.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtParentPhone.PlaceholderText = "Enter student\'s parent phone number";
            this.txtParentPhone.ReadOnly = false;
            this.txtParentPhone.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtParentPhone.SelectedText = "";
            this.txtParentPhone.SelectionLength = 0;
            this.txtParentPhone.SelectionStart = 0;
            this.txtParentPhone.ShortcutsEnabled = true;
            this.txtParentPhone.Size = new System.Drawing.Size(197, 41);
            this.txtParentPhone.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtParentPhone.TabIndex = 98;
            this.txtParentPhone.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtParentPhone.TextMarginBottom = 0;
            this.txtParentPhone.TextMarginLeft = 3;
            this.txtParentPhone.TextMarginTop = 0;
            this.txtParentPhone.TextPlaceholder = "Enter student\'s parent phone number";
            this.txtParentPhone.UseSystemPasswordChar = false;
            this.txtParentPhone.WordWrap = true;
            // 
            // txtStudentAddress
            // 
            this.txtStudentAddress.AcceptsReturn = false;
            this.txtStudentAddress.AcceptsTab = false;
            this.txtStudentAddress.AnimationSpeed = 200;
            this.txtStudentAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStudentAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStudentAddress.BackColor = System.Drawing.Color.Transparent;
            this.txtStudentAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStudentAddress.BackgroundImage")));
            this.txtStudentAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtStudentAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStudentAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtStudentAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStudentAddress.BorderRadius = 10;
            this.txtStudentAddress.BorderThickness = 1;
            this.txtStudentAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStudentAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtStudentAddress.DefaultText = "";
            this.txtStudentAddress.FillColor = System.Drawing.Color.White;
            this.txtStudentAddress.HideSelection = true;
            this.txtStudentAddress.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtStudentAddress.IconLeft")));
            this.txtStudentAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentAddress.IconPadding = 10;
            this.txtStudentAddress.IconRight = null;
            this.txtStudentAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentAddress.Lines = new string[0];
            this.txtStudentAddress.Location = new System.Drawing.Point(386, 242);
            this.txtStudentAddress.MaxLength = 32767;
            this.txtStudentAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStudentAddress.Modified = false;
            this.txtStudentAddress.Multiline = false;
            this.txtStudentAddress.Name = "txtStudentAddress";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentAddress.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStudentAddress.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentAddress.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentAddress.OnIdleState = stateProperties56;
            this.txtStudentAddress.Padding = new System.Windows.Forms.Padding(3);
            this.txtStudentAddress.PasswordChar = '\0';
            this.txtStudentAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStudentAddress.PlaceholderText = "Enter student\'s address";
            this.txtStudentAddress.ReadOnly = false;
            this.txtStudentAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStudentAddress.SelectedText = "";
            this.txtStudentAddress.SelectionLength = 0;
            this.txtStudentAddress.SelectionStart = 0;
            this.txtStudentAddress.ShortcutsEnabled = true;
            this.txtStudentAddress.Size = new System.Drawing.Size(362, 41);
            this.txtStudentAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStudentAddress.TabIndex = 99;
            this.txtStudentAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStudentAddress.TextMarginBottom = 0;
            this.txtStudentAddress.TextMarginLeft = 3;
            this.txtStudentAddress.TextMarginTop = 0;
            this.txtStudentAddress.TextPlaceholder = "Enter student\'s address";
            this.txtStudentAddress.UseSystemPasswordChar = false;
            this.txtStudentAddress.WordWrap = true;
            // 
            // txtStudentName
            // 
            this.txtStudentName.AcceptsReturn = false;
            this.txtStudentName.AcceptsTab = false;
            this.txtStudentName.AnimationSpeed = 200;
            this.txtStudentName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtStudentName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtStudentName.BackColor = System.Drawing.Color.Transparent;
            this.txtStudentName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtStudentName.BackgroundImage")));
            this.txtStudentName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtStudentName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtStudentName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtStudentName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtStudentName.BorderRadius = 10;
            this.txtStudentName.BorderThickness = 1;
            this.txtStudentName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtStudentName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtStudentName.DefaultText = "";
            this.txtStudentName.FillColor = System.Drawing.Color.White;
            this.txtStudentName.HideSelection = true;
            this.txtStudentName.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtStudentName.IconLeft")));
            this.txtStudentName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentName.IconPadding = 10;
            this.txtStudentName.IconRight = null;
            this.txtStudentName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtStudentName.Lines = new string[0];
            this.txtStudentName.Location = new System.Drawing.Point(386, 150);
            this.txtStudentName.MaxLength = 32767;
            this.txtStudentName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtStudentName.Modified = false;
            this.txtStudentName.Multiline = false;
            this.txtStudentName.Name = "txtStudentName";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentName.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtStudentName.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentName.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtStudentName.OnIdleState = stateProperties60;
            this.txtStudentName.Padding = new System.Windows.Forms.Padding(3);
            this.txtStudentName.PasswordChar = '\0';
            this.txtStudentName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtStudentName.PlaceholderText = "Enter student\'s name";
            this.txtStudentName.ReadOnly = false;
            this.txtStudentName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtStudentName.SelectedText = "";
            this.txtStudentName.SelectionLength = 0;
            this.txtStudentName.SelectionStart = 0;
            this.txtStudentName.ShortcutsEnabled = true;
            this.txtStudentName.Size = new System.Drawing.Size(362, 41);
            this.txtStudentName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtStudentName.TabIndex = 100;
            this.txtStudentName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtStudentName.TextMarginBottom = 0;
            this.txtStudentName.TextMarginLeft = 3;
            this.txtStudentName.TextMarginTop = 0;
            this.txtStudentName.TextPlaceholder = "Enter student\'s name";
            this.txtStudentName.UseSystemPasswordChar = false;
            this.txtStudentName.WordWrap = true;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel4.Location = new System.Drawing.Point(386, 301);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(124, 26);
            this.bunifuLabel4.TabIndex = 92;
            this.bunifuLabel4.Text = "Parent Phone";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel1.Location = new System.Drawing.Point(386, 210);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(74, 26);
            this.bunifuLabel1.TabIndex = 93;
            this.bunifuLabel1.Text = " Address";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lbl_Class
            // 
            this.lbl_Class.AllowParentOverrides = false;
            this.lbl_Class.AutoEllipsis = false;
            this.lbl_Class.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbl_Class.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbl_Class.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_Class.ForeColor = System.Drawing.Color.DarkGray;
            this.lbl_Class.Location = new System.Drawing.Point(624, 396);
            this.lbl_Class.Name = "lbl_Class";
            this.lbl_Class.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbl_Class.Size = new System.Drawing.Size(0, 0);
            this.lbl_Class.TabIndex = 94;
            this.lbl_Class.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbl_Class.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel5.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel5.Location = new System.Drawing.Point(568, 396);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(0, 0);
            this.bunifuLabel5.TabIndex = 95;
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel3.Location = new System.Drawing.Point(386, 118);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(55, 26);
            this.bunifuLabel3.TabIndex = 97;
            this.bunifuLabel3.Text = "Name";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel2.Font = new System.Drawing.Font("Garamond", 19.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.DarkRed;
            this.bunifuLabel2.Location = new System.Drawing.Point(423, 62);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(273, 37);
            this.bunifuLabel2.TabIndex = 91;
            this.bunifuLabel2.Text = "Edit Student Profile";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // pic_StudentAvatar
            // 
            this.pic_StudentAvatar.AllowFocused = false;
            this.pic_StudentAvatar.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.pic_StudentAvatar.AutoSizeHeight = true;
            this.pic_StudentAvatar.BorderRadius = 134;
            this.pic_StudentAvatar.Image = ((System.Drawing.Image)(resources.GetObject("pic_StudentAvatar.Image")));
            this.pic_StudentAvatar.IsCircle = true;
            this.pic_StudentAvatar.Location = new System.Drawing.Point(54, 101);
            this.pic_StudentAvatar.Name = "pic_StudentAvatar";
            this.pic_StudentAvatar.Size = new System.Drawing.Size(268, 268);
            this.pic_StudentAvatar.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pic_StudentAvatar.TabIndex = 90;
            this.pic_StudentAvatar.TabStop = false;
            this.pic_StudentAvatar.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel6.Font = new System.Drawing.Font("Garamond", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.Olive;
            this.bunifuLabel6.Location = new System.Drawing.Point(386, 396);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(77, 26);
            this.bunifuLabel6.TabIndex = 104;
            this.bunifuLabel6.Text = "ID Class";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // errorProvider1
            // 
            this.errorProvider1.ContainerControl = this;
            // 
            // bunifuSnackbar1
            // 
            this.bunifuSnackbar1.AllowDragging = false;
            this.bunifuSnackbar1.AllowMultipleViews = true;
            this.bunifuSnackbar1.ClickToClose = true;
            this.bunifuSnackbar1.DoubleClickToClose = true;
            this.bunifuSnackbar1.DurationAfterIdle = 3000;
            this.bunifuSnackbar1.ErrorOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.ErrorOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.ErrorOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.ErrorOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.ErrorOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(204)))), ((int)(((byte)(199)))));
            this.bunifuSnackbar1.ErrorOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.ErrorOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.ErrorOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon")));
            this.bunifuSnackbar1.ErrorOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.FadeCloseIcon = false;
            this.bunifuSnackbar1.Host = Bunifu.UI.WinForms.BunifuSnackbar.Hosts.FormOwner;
            this.bunifuSnackbar1.InformationOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.InformationOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.InformationOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.InformationOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(145)))), ((int)(((byte)(213)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.InformationOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.InformationOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.InformationOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon1")));
            this.bunifuSnackbar1.InformationOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.Margin = 10;
            this.bunifuSnackbar1.MaximumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.MaximumViews = 7;
            this.bunifuSnackbar1.MessageRightMargin = 15;
            this.bunifuSnackbar1.MinimumSize = new System.Drawing.Size(0, 0);
            this.bunifuSnackbar1.ShowBorders = false;
            this.bunifuSnackbar1.ShowCloseIcon = false;
            this.bunifuSnackbar1.ShowIcon = true;
            this.bunifuSnackbar1.ShowShadows = true;
            this.bunifuSnackbar1.SuccessOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.SuccessOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.SuccessOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.SuccessOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.SuccessOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(255)))), ((int)(((byte)(237)))));
            this.bunifuSnackbar1.SuccessOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.SuccessOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.SuccessOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon2")));
            this.bunifuSnackbar1.SuccessOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ViewsMargin = 7;
            this.bunifuSnackbar1.WarningOptions.ActionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(255)))));
            this.bunifuSnackbar1.WarningOptions.ActionBorderRadius = 1;
            this.bunifuSnackbar1.WarningOptions.ActionFont = new System.Drawing.Font("Segoe UI", 8.25F, System.Drawing.FontStyle.Bold);
            this.bunifuSnackbar1.WarningOptions.ActionForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.BackColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.BorderColor = System.Drawing.Color.White;
            this.bunifuSnackbar1.WarningOptions.CloseIconColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(229)))), ((int)(((byte)(143)))));
            this.bunifuSnackbar1.WarningOptions.Font = new System.Drawing.Font("Segoe UI", 9.75F);
            this.bunifuSnackbar1.WarningOptions.ForeColor = System.Drawing.Color.Black;
            this.bunifuSnackbar1.WarningOptions.Icon = ((System.Drawing.Image)(resources.GetObject("resource.Icon3")));
            this.bunifuSnackbar1.WarningOptions.IconLeftMargin = 12;
            this.bunifuSnackbar1.ZoomCloseIcon = true;
            // 
            // openFilePic
            // 
            this.openFilePic.FileName = "openFileDialog1";
            // 
            // btnUpload
            // 
            this.btnUpload.AllowAnimations = true;
            this.btnUpload.AllowMouseEffects = true;
            this.btnUpload.AllowToggling = false;
            this.btnUpload.AnimationSpeed = 200;
            this.btnUpload.AutoGenerateColors = false;
            this.btnUpload.AutoRoundBorders = false;
            this.btnUpload.AutoSizeLeftIcon = true;
            this.btnUpload.AutoSizeRightIcon = true;
            this.btnUpload.BackColor = System.Drawing.Color.Transparent;
            this.btnUpload.BackColor1 = System.Drawing.Color.Navy;
            this.btnUpload.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpload.BackgroundImage")));
            this.btnUpload.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.btnUpload.ButtonText = "Upload";
            this.btnUpload.ButtonTextMarginLeft = 0;
            this.btnUpload.ColorContrastOnClick = 45;
            this.btnUpload.ColorContrastOnHover = 45;
            this.btnUpload.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnUpload.CustomizableEdges = borderEdges6;
            this.btnUpload.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpload.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpload.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpload.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpload.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUpload.Font = new System.Drawing.Font("Garamond", 12F);
            this.btnUpload.ForeColor = System.Drawing.Color.White;
            this.btnUpload.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpload.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpload.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUpload.IconMarginLeft = 11;
            this.btnUpload.IconPadding = 10;
            this.btnUpload.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpload.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpload.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpload.IconSize = 25;
            this.btnUpload.IdleBorderColor = System.Drawing.Color.FloralWhite;
            this.btnUpload.IdleBorderRadius = 20;
            this.btnUpload.IdleBorderThickness = 1;
            this.btnUpload.IdleFillColor = System.Drawing.Color.Navy;
            this.btnUpload.IdleIconLeftImage = null;
            this.btnUpload.IdleIconRightImage = null;
            this.btnUpload.IndicateFocus = false;
            this.btnUpload.Location = new System.Drawing.Point(108, 430);
            this.btnUpload.Name = "btnUpload";
            this.btnUpload.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpload.OnDisabledState.BorderRadius = 20;
            this.btnUpload.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpload.OnDisabledState.BorderThickness = 1;
            this.btnUpload.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpload.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpload.OnDisabledState.IconLeftImage = null;
            this.btnUpload.OnDisabledState.IconRightImage = null;
            this.btnUpload.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpload.onHoverState.BorderRadius = 20;
            this.btnUpload.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpload.onHoverState.BorderThickness = 1;
            this.btnUpload.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpload.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUpload.onHoverState.IconLeftImage = null;
            this.btnUpload.onHoverState.IconRightImage = null;
            this.btnUpload.OnIdleState.BorderColor = System.Drawing.Color.FloralWhite;
            this.btnUpload.OnIdleState.BorderRadius = 20;
            this.btnUpload.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Dash;
            this.btnUpload.OnIdleState.BorderThickness = 1;
            this.btnUpload.OnIdleState.FillColor = System.Drawing.Color.Navy;
            this.btnUpload.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUpload.OnIdleState.IconLeftImage = null;
            this.btnUpload.OnIdleState.IconRightImage = null;
            this.btnUpload.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpload.OnPressedState.BorderRadius = 20;
            this.btnUpload.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpload.OnPressedState.BorderThickness = 1;
            this.btnUpload.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpload.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUpload.OnPressedState.IconLeftImage = null;
            this.btnUpload.OnPressedState.IconRightImage = null;
            this.btnUpload.Size = new System.Drawing.Size(145, 39);
            this.btnUpload.TabIndex = 107;
            this.btnUpload.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpload.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpload.TextMarginLeft = 0;
            this.btnUpload.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUpload.UseDefaultRadiusAndThickness = true;
            this.btnUpload.Click += new System.EventHandler(this.btnUpload_Click_1);
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = false;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            this.bunifuFormDock1.FormDragging += new System.EventHandler<Bunifu.UI.WinForms.BunifuFormDock.FormDraggingEventArgs>(this.bunifuFormDock1_FormDragging);
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 35;
            this.bunifuElipse1.TargetControl = this;
            // 
            // drp_Classroom
            // 
            this.drp_Classroom.BackColor = System.Drawing.Color.Transparent;
            this.drp_Classroom.BackgroundColor = System.Drawing.Color.White;
            this.drp_Classroom.BorderColor = System.Drawing.Color.Silver;
            this.drp_Classroom.BorderRadius = 8;
            this.drp_Classroom.Color = System.Drawing.Color.Silver;
            this.drp_Classroom.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.drp_Classroom.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drp_Classroom.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.drp_Classroom.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.drp_Classroom.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.drp_Classroom.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.drp_Classroom.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.drp_Classroom.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.drp_Classroom.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.drp_Classroom.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drp_Classroom.FillDropDown = true;
            this.drp_Classroom.FillIndicator = false;
            this.drp_Classroom.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.drp_Classroom.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.drp_Classroom.ForeColor = System.Drawing.Color.Black;
            this.drp_Classroom.FormattingEnabled = true;
            this.drp_Classroom.Icon = null;
            this.drp_Classroom.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drp_Classroom.IndicatorColor = System.Drawing.Color.Gray;
            this.drp_Classroom.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.drp_Classroom.ItemBackColor = System.Drawing.Color.White;
            this.drp_Classroom.ItemBorderColor = System.Drawing.Color.White;
            this.drp_Classroom.ItemForeColor = System.Drawing.Color.Black;
            this.drp_Classroom.ItemHeight = 26;
            this.drp_Classroom.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.drp_Classroom.ItemHighLightForeColor = System.Drawing.Color.White;
            this.drp_Classroom.ItemTopMargin = 3;
            this.drp_Classroom.Location = new System.Drawing.Point(386, 428);
            this.drp_Classroom.Name = "drp_Classroom";
            this.drp_Classroom.Size = new System.Drawing.Size(150, 32);
            this.drp_Classroom.TabIndex = 128;
            this.drp_Classroom.Text = "Class";
            this.drp_Classroom.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.drp_Classroom.TextLeftMargin = 5;
            // 
            // lbl_ClassId
            // 
            this.lbl_ClassId.AcceptsReturn = false;
            this.lbl_ClassId.AcceptsTab = false;
            this.lbl_ClassId.AnimationSpeed = 200;
            this.lbl_ClassId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lbl_ClassId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lbl_ClassId.BackColor = System.Drawing.Color.Transparent;
            this.lbl_ClassId.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lbl_ClassId.BackgroundImage")));
            this.lbl_ClassId.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.lbl_ClassId.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lbl_ClassId.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.lbl_ClassId.BorderColorIdle = System.Drawing.SystemColors.Control;
            this.lbl_ClassId.BorderRadius = 10;
            this.lbl_ClassId.BorderThickness = 1;
            this.lbl_ClassId.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lbl_ClassId.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lbl_ClassId.DefaultFont = new System.Drawing.Font("Garamond", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lbl_ClassId.DefaultText = "";
            this.lbl_ClassId.FillColor = System.Drawing.SystemColors.Control;
            this.lbl_ClassId.ForeColor = System.Drawing.Color.Olive;
            this.lbl_ClassId.HideSelection = true;
            this.lbl_ClassId.IconLeft = null;
            this.lbl_ClassId.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lbl_ClassId.IconPadding = 10;
            this.lbl_ClassId.IconRight = null;
            this.lbl_ClassId.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lbl_ClassId.Lines = new string[0];
            this.lbl_ClassId.Location = new System.Drawing.Point(14, 62);
            this.lbl_ClassId.MaxLength = 32767;
            this.lbl_ClassId.MinimumSize = new System.Drawing.Size(1, 1);
            this.lbl_ClassId.Modified = false;
            this.lbl_ClassId.Multiline = false;
            this.lbl_ClassId.Name = "lbl_ClassId";
            stateProperties65.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lbl_ClassId.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties66.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties66.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lbl_ClassId.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lbl_ClassId.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.SystemColors.Control;
            stateProperties68.FillColor = System.Drawing.SystemColors.Control;
            stateProperties68.ForeColor = System.Drawing.Color.Olive;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lbl_ClassId.OnIdleState = stateProperties68;
            this.lbl_ClassId.Padding = new System.Windows.Forms.Padding(3);
            this.lbl_ClassId.PasswordChar = '\0';
            this.lbl_ClassId.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.lbl_ClassId.PlaceholderText = "id";
            this.lbl_ClassId.ReadOnly = true;
            this.lbl_ClassId.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lbl_ClassId.SelectedText = "";
            this.lbl_ClassId.SelectionLength = 0;
            this.lbl_ClassId.SelectionStart = 0;
            this.lbl_ClassId.ShortcutsEnabled = true;
            this.lbl_ClassId.Size = new System.Drawing.Size(41, 43);
            this.lbl_ClassId.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lbl_ClassId.TabIndex = 110;
            this.lbl_ClassId.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lbl_ClassId.TextMarginBottom = 0;
            this.lbl_ClassId.TextMarginLeft = 3;
            this.lbl_ClassId.TextMarginTop = 0;
            this.lbl_ClassId.TextPlaceholder = "id";
            this.lbl_ClassId.UseSystemPasswordChar = false;
            this.lbl_ClassId.WordWrap = true;
            // 
            // txtParentName
            // 
            this.txtParentName.AcceptsReturn = false;
            this.txtParentName.AcceptsTab = false;
            this.txtParentName.AnimationSpeed = 200;
            this.txtParentName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtParentName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtParentName.BackColor = System.Drawing.Color.Transparent;
            this.txtParentName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtParentName.BackgroundImage")));
            this.txtParentName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtParentName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtParentName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtParentName.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtParentName.BorderRadius = 10;
            this.txtParentName.BorderThickness = 1;
            this.txtParentName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtParentName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtParentName.DefaultText = "";
            this.txtParentName.FillColor = System.Drawing.Color.White;
            this.txtParentName.HideSelection = true;
            this.txtParentName.IconLeft = ((System.Drawing.Image)(resources.GetObject("txtParentName.IconLeft")));
            this.txtParentName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentName.IconPadding = 10;
            this.txtParentName.IconRight = null;
            this.txtParentName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtParentName.Lines = new string[0];
            this.txtParentName.Location = new System.Drawing.Point(589, 333);
            this.txtParentName.MaxLength = 32767;
            this.txtParentName.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtParentName.Modified = false;
            this.txtParentName.Multiline = false;
            this.txtParentName.Name = "txtParentName";
            stateProperties69.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentName.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties70.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties70.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtParentName.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentName.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Silver;
            stateProperties72.FillColor = System.Drawing.Color.White;
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtParentName.OnIdleState = stateProperties72;
            this.txtParentName.Padding = new System.Windows.Forms.Padding(3);
            this.txtParentName.PasswordChar = '\0';
            this.txtParentName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtParentName.PlaceholderText = "Enter student\'s parent phone number";
            this.txtParentName.ReadOnly = false;
            this.txtParentName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtParentName.SelectedText = "";
            this.txtParentName.SelectionLength = 0;
            this.txtParentName.SelectionStart = 0;
            this.txtParentName.ShortcutsEnabled = true;
            this.txtParentName.Size = new System.Drawing.Size(159, 41);
            this.txtParentName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtParentName.TabIndex = 98;
            this.txtParentName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtParentName.TextMarginBottom = 0;
            this.txtParentName.TextMarginLeft = 3;
            this.txtParentName.TextMarginTop = 0;
            this.txtParentName.TextPlaceholder = "Enter student\'s parent phone number";
            this.txtParentName.UseSystemPasswordChar = false;
            this.txtParentName.WordWrap = true;
            // 
            // dtp_StudentDOB
            // 
            this.dtp_StudentDOB.BackColor = System.Drawing.Color.White;
            this.dtp_StudentDOB.BorderRadius = 1;
            this.dtp_StudentDOB.CalendarForeColor = System.Drawing.Color.Navy;
            this.dtp_StudentDOB.CalendarMonthBackground = System.Drawing.SystemColors.HighlightText;
            this.dtp_StudentDOB.CalendarTrailingForeColor = System.Drawing.SystemColors.Control;
            this.dtp_StudentDOB.Color = System.Drawing.Color.Silver;
            this.dtp_StudentDOB.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtp_StudentDOB.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtp_StudentDOB.DisabledColor = System.Drawing.Color.Gray;
            this.dtp_StudentDOB.DisplayWeekNumbers = false;
            this.dtp_StudentDOB.DPHeight = 0;
            this.dtp_StudentDOB.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtp_StudentDOB.FillDatePicker = false;
            this.dtp_StudentDOB.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtp_StudentDOB.ForeColor = System.Drawing.Color.Black;
            this.dtp_StudentDOB.Icon = ((System.Drawing.Image)(resources.GetObject("dtp_StudentDOB.Icon")));
            this.dtp_StudentDOB.IconColor = System.Drawing.Color.Gray;
            this.dtp_StudentDOB.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtp_StudentDOB.LeftTextMargin = 5;
            this.dtp_StudentDOB.Location = new System.Drawing.Point(86, 390);
            this.dtp_StudentDOB.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtp_StudentDOB.Name = "dtp_StudentDOB";
            this.dtp_StudentDOB.Size = new System.Drawing.Size(196, 32);
            this.dtp_StudentDOB.TabIndex = 132;
            // 
            // txt_Id
            // 
            this.txt_Id.AcceptsReturn = false;
            this.txt_Id.AcceptsTab = false;
            this.txt_Id.AnimationSpeed = 200;
            this.txt_Id.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txt_Id.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txt_Id.BackColor = System.Drawing.Color.Transparent;
            this.txt_Id.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txt_Id.BackgroundImage")));
            this.txt_Id.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txt_Id.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txt_Id.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txt_Id.BorderColorIdle = System.Drawing.SystemColors.Control;
            this.txt_Id.BorderRadius = 10;
            this.txt_Id.BorderThickness = 1;
            this.txt_Id.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txt_Id.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Id.DefaultFont = new System.Drawing.Font("Garamond", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.txt_Id.DefaultText = "";
            this.txt_Id.FillColor = System.Drawing.SystemColors.Control;
            this.txt_Id.ForeColor = System.Drawing.Color.Olive;
            this.txt_Id.HideSelection = true;
            this.txt_Id.IconLeft = null;
            this.txt_Id.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Id.IconPadding = 10;
            this.txt_Id.IconRight = null;
            this.txt_Id.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txt_Id.Lines = new string[0];
            this.txt_Id.Location = new System.Drawing.Point(16, 101);
            this.txt_Id.MaxLength = 32767;
            this.txt_Id.MinimumSize = new System.Drawing.Size(1, 1);
            this.txt_Id.Modified = false;
            this.txt_Id.Multiline = false;
            this.txt_Id.Name = "txt_Id";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Id.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txt_Id.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Id.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.SystemColors.Control;
            stateProperties64.FillColor = System.Drawing.SystemColors.Control;
            stateProperties64.ForeColor = System.Drawing.Color.Olive;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txt_Id.OnIdleState = stateProperties64;
            this.txt_Id.Padding = new System.Windows.Forms.Padding(3);
            this.txt_Id.PasswordChar = '\0';
            this.txt_Id.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.txt_Id.PlaceholderText = "id";
            this.txt_Id.ReadOnly = true;
            this.txt_Id.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txt_Id.SelectedText = "";
            this.txt_Id.SelectionLength = 0;
            this.txt_Id.SelectionStart = 0;
            this.txt_Id.ShortcutsEnabled = true;
            this.txt_Id.Size = new System.Drawing.Size(41, 43);
            this.txt_Id.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txt_Id.TabIndex = 110;
            this.txt_Id.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txt_Id.TextMarginBottom = 0;
            this.txt_Id.TextMarginLeft = 3;
            this.txt_Id.TextMarginTop = 0;
            this.txt_Id.TextPlaceholder = "id";
            this.txt_Id.UseSystemPasswordChar = false;
            this.txt_Id.WordWrap = true;
            // 
            // FrmStudent
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 21F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(784, 487);
            this.Controls.Add(this.dtp_StudentDOB);
            this.Controls.Add(this.drp_Classroom);
            this.Controls.Add(this.txt_Id);
            this.Controls.Add(this.lbl_ClassId);
            this.Controls.Add(this.btnUpload);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.btnSave);
            this.Controls.Add(this.txtParentName);
            this.Controls.Add(this.txtParentPhone);
            this.Controls.Add(this.txtStudentAddress);
            this.Controls.Add(this.txtStudentName);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.bunifuLabel1);
            this.Controls.Add(this.lbl_Class);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.pic_StudentAvatar);
            this.HeaderBackColor = System.Drawing.Color.Navy;
            this.Name = "FrmStudent";
            this.Text = "Edit student Information [Adminstrator]";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.FrmStudent_FormClosing);
            this.Load += new System.EventHandler(this.FrmStudent_Load);
            this.Controls.SetChildIndex(this.pic_StudentAvatar, 0);
            this.Controls.SetChildIndex(this.bunifuLabel2, 0);
            this.Controls.SetChildIndex(this.bunifuLabel3, 0);
            this.Controls.SetChildIndex(this.bunifuLabel5, 0);
            this.Controls.SetChildIndex(this.lbl_Class, 0);
            this.Controls.SetChildIndex(this.bunifuLabel1, 0);
            this.Controls.SetChildIndex(this.bunifuLabel4, 0);
            this.Controls.SetChildIndex(this.txtStudentName, 0);
            this.Controls.SetChildIndex(this.txtStudentAddress, 0);
            this.Controls.SetChildIndex(this.txtParentPhone, 0);
            this.Controls.SetChildIndex(this.txtParentName, 0);
            this.Controls.SetChildIndex(this.btnSave, 0);
            this.Controls.SetChildIndex(this.bunifuLabel6, 0);
            this.Controls.SetChildIndex(this.btnUpload, 0);
            this.Controls.SetChildIndex(this.lbl_ClassId, 0);
            this.Controls.SetChildIndex(this.txt_Id, 0);
            this.Controls.SetChildIndex(this.drp_Classroom, 0);
            this.Controls.SetChildIndex(this.dtp_StudentDOB, 0);
            ((System.ComponentModel.ISupportInitialize)(this.pic_StudentAvatar)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.errorProvider1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSave;
        private Bunifu.UI.WinForms.BunifuTextBox txtParentPhone;
        private Bunifu.UI.WinForms.BunifuTextBox txtStudentAddress;
        private Bunifu.UI.WinForms.BunifuTextBox txtStudentName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuLabel lbl_Class;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuPictureBox pic_StudentAvatar;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private System.Windows.Forms.ErrorProvider errorProvider1;
        private Bunifu.UI.WinForms.BunifuSnackbar bunifuSnackbar1;
        private System.Windows.Forms.OpenFileDialog openFilePic;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUpload;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuDropdown drp_Classroom;
        private Bunifu.UI.WinForms.BunifuTextBox lbl_ClassId;
        private Bunifu.UI.WinForms.BunifuTextBox txtParentName;
        private Bunifu.UI.WinForms.BunifuDatePicker dtp_StudentDOB;
        private Bunifu.UI.WinForms.BunifuTextBox txt_Id;
    }
}